server:
  port: 8888

spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/gpleo/spring-cloud-config-demo.git
          clone-on-start: true
          search-paths: config
        encrypt:
          enabled: false
security:
  basic:
    enabled: true
  user:
    name: config
    password: config
